// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvhskhnmdvkvyvrwggwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2aHNraG5tZHZrdnl2cndnZ3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTQzNzMsImV4cCI6MjA2NDc5MDM3M30.1VWJmWvSdOV363M5QzFhdgUrZSmqBKiJtid1v_THdqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);